website/models.py
from . import db
from flask_login import UserMixin
from datetime import datetime

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    date_created = db.Column(db.DateTime, default=datetime.now)
    posts = db.relationship("Post", backref="user", passive_deletes=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.now)
    author = db.Column(db.Integer, db.ForeignKey(
        'user.id', ondelete="CASCADE"), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "helloworld"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User, Post

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
     if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
            print('Created Database!')
        

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from .models import User
from . import db
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if user: 
                if check_password_hash(user.password, password):
                    flash("Logged in!", category='Sucess')
                    login_user(user, remember=True)
                    return redirect(url_for('views.home'))
                else:
                    flash("Password is incorrect!", category="error")
        else:
            flash("Email is incorrect!", category="error")
        


    return render_template("login.html", useri = current_user)

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        username = request.form.get("username")
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
    
        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        if email_exists:
            flash('Email already in use.', category='error')
        elif len(email) < 10:
            flash("Email is invalid", category="error")
        elif username_exists:
            flash('Username already in use', category="error")
        elif password1 != password2:
            flash("Passwords don't match", category="error")
        elif len(username) < 2:
            flash("Username is too short", category="error")
        elif len(password1) < 2:
            flash("Password is too short", category="error")
        
        else:
            new_user = User(email=email, username=username, password= generate_password_hash(password1, method='scrypt'))
            print("a")
            db.session.add(new_user)
            print("b")
            db.session.commit()
            print("c")
            login_user(new_user, remember=True)
            flash("Signed up!", category='Sucess')
            return redirect(url_for('views.home'))

    return render_template("signup.html", useri = current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User
from . import db

views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)  # Get the current page number, default is 1
    posts = Post.query.order_by(Post.date_created.desc()).paginate(page=page, per_page=10)
    templates = render_template("home.html", useri = current_user, posts=posts)
    return templates


@views.route("/createpost", methods=["GET", "POST"])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get("text")
        if not text:
            flash("Post cannot be empty", category="error")
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash("Post created!", category="success")
            return redirect(url_for("views.home"))

    return render_template("create_post.html", useri=current_user)

@views.route('/delete_post/<int:post_id>', methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.user:
        flash("You cannot delete this post", category="error")
    else:
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted successfully", category="success")
    return redirect(url_for('views.home'))

@views.route('posts/<username>')
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()
    if user:
        posts = Post.query.filter_by(author=user.id).all()
        return render_template("posts.html", user=user, posts=posts)
    else:
        return "User not found", 404

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{% block title%}{%endblock%}</title>
</head>
<body style="background-color: black;">
    <ul class="navbar">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="/home" style="font-size: 33px; font-weight: 800;">Junior Blog</a>
      </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/home">Home</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="/logout">Log out</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sign-up">Sign Up</a>
        </li>
        {% endif %}
      </ul>

    <div class="container">
        {%with messages = get_flashed_messages(with_categories=True)%}
            {% if messages %}
                {%for category, message in messages%}
                    {% if category == "error" %}
                        <div class="flash-error">
                        {{message}}
                        </div>
                    {% else %}
                        <div class="flash-success">
                        {{message}}
                        </div>
                    {% endif %} 
                {%endfor%}
            {% endif %}
        {% endwith %}
        {% block content%} {%endblock%}  
        
     </div> 



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

website/templates/create_post.html
{% extends "base.html"%}
{% block title%} Login {%endblock%}

{% block content%} 
<h2>Create a post</h2>
<form method="POST">
<textarea name="text" id="text" method="POST"></textarea>
<button type="submit" class="link"> Post </button>
</form>

{%endblock%}

website/templates/home.html
{% extends "base.html"%}
{% block title%} Home {%endblock%}
{% block content%} 

<h1 class="my-4">Complaints</h1>
<div class="link">
    <a href="/createpost" >Add your complain</a>
</div>

<div class="container">
    {% for post in posts %}
   
    <div class="container posts-content">
        <div class="row">
                <div class="card mb-8">
                  <div class="card-body">
                    <div class="media mb-3">
                      <div class="media-body ml-3">
                        <a href="posts/{{post.user.username}}">{{post.user.username}}</a>
                        <div class="text-muted small">Created on: {{ post.date_created.strftime('%Y-%m-%d %H:%M') }}</div>
                      </div>
                    </div>
                <p>{{post.text}}</p>
                   
                    <a href="javascript:void(0)" class="ui-rect ui-bg-cover" style="background-image: url('https://bootdey.com/img/Content/avatar/avatar3.png');"></a>
                  </div>
                  <div class="card-footer">
                    <a href="javascript:void(0)" class="d-inline-block text-muted">
                      <small class="align-middle">123 Likes</small>
                    </a>
                    <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                        <small class="align-middle">12 Comments</small>
                    </a>
                    <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                      <small class="align-middle">Repost</small>
                    </a>
                    {% if current_user == post.user %}
                    <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                        <form action="{{url_for('views.delete_post', post_id=post.id)}}" method="POST"
                        class="d-inline-block text-muted ml-3 form-group">
                        <button type="submit" class="btn d-md-flex justify-content-md-end"> Delete</button>
                     </form>
                    </a> 
                    {% endif %}
                    
                  </div>
                </div>
            </div>
        
    </div>
    {% endfor %}
</div>

<div class="loadmore text-center my-4">
    {% if posts.has_next %}
        <a href="{{ url_for('views.home', page=posts.next_num) }}" class="btn btn-outline-secondary">Load More</a>
    {% endif %}
</div>

{%endblock%}

website/templates/login.html
<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
{% extends "base.html"%}
{% block title%} Login {%endblock%}
{% block content%} 
<form method="POST" class="form">
    <h3>Login to create and see posts!</h3>
    <label class="label" for="email">What is your Email?</label> <br>
    <input type="text" id="email" name="email" placeholder="Enter Email"/> <br>
    <label class="label" for="email">Put a Password</label> <br>
    <input type="text" id="password" name="password" placeholder="Enter Password"/>
    <div class="button">
        <button type="submit">Login</button>
        </div>
</form>

{%endblock%}

website/templates/logout.html
{% extends "base.html"%}
{% block title%} Home {%endblock%}
{% block content%} <h1>Welcome to Daniel's Blog! </h1> {%endblock%}

website/templates/nav.html
{% extends "base.html"%}
{% block title%} Home {%endblock%}
{% block nav%} 

    <ul class="navbar">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="/home" style="font-size: 33px; font-weight: 800;">Junior Blog</a>
      </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/home">Home</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="/logout">Log out</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sign-up">Sign Up</a>
        </li>
        {% endif %}
      </ul>

    <div class="container">
        {%with messages = get_flashed_messages(with_categories=True)%}
            {% if messages %}
                {%for category, message in messages%}
                    {% if category == "error" %}
                        <div class="flash-error">
                        {{message}}
                        </div>
                    {% else %}
                        <div class="flash-success">
                        {{message}}
                        </div>
                    {% endif %} 
                {%endfor%}
            {% endif %}
        {% endwith %}

{% endblock %}

website/templates/posts.html
{% extends "base.html"%}
{% block title%} Login {%endblock%}
{% block content%}
 

<h1>{{ user.username }}'s Posts</h1>

{% for post in posts %}
<div class="container posts-content">
    <div class="row">
        <div class="card mb-8">
            <div class="card-body">
                <div class="media mb-3">
                    <div class="media-body ml-3">
                        <div class="text-muted small">Created on: {{ post.date_created.strftime('%Y-%m-%d %H:%M') }}</div>
                    </div>
                </div>
                <p>{{ post.text }}</p>
                <a href="javascript:void(0)" class="ui-rect ui-bg-cover" style="background-image: url('https://bootdey.com/img/Content/avatar/avatar3.png');"></a>
            </div>
            <div class="card-footer">
                <a href="javascript:void(0)" class="d-inline-block text-muted">
                    <small class="align-middle">123 Likes</small>
                </a>
                <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                    <small class="align-middle">12 Comments</small>
                </a>
                <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                    <small class="align-middle">Repost</small>
                </a>
                {% if current_user == post.user %}
                <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                    <form action="{{ url_for('views.delete_post', post_id=post.id) }}" method="POST" class="d-inline-block text-muted ml-3 form-group">
                        <button type="submit" class="btn d-md-flex justify-content-md-end"> Delete</button>
                    </form>
                </a> 
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}

 
 {%endblock%}

website/templates/posts_div.html
{%extends "base.html"%}

website/templates/signup.html
<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
{% extends "base.html"%}
{% block title%} Login {%endblock%}
{% block content%} 
<form method="POST" class="form">
    <h3>Sign Up is so easy!</h3>
    <label class="label" for="email">Email</label> <br>
    <input type="text" id="email" name="email" placeholder="Enter Email"/> <br>
    <label class="label" for="username">Username</label> <br>
    <input type="text" id="username" name="username" placeholder="Enter Username"/> <br>
    <label class="label" for="email">Password</label> <br>
    <input type="text" id="password1" name="password1" placeholder="Enter Password"/> <br>
    <label class="label" for="email">Enter Password Again</label> <br>
    <input type="text" id="password2" name="password2" placeholder="Enter Password Again"/>
    <div class="button">
        <button type="submit">Sign Up</button>
        </div>
</form>

{%endblock%}